### ISSUE TITLE
Why? What? How?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/github-backup#1]
This repo was born out of the need identified in: https://github.com/dwyl/github-reference/issues/15

## Why?

As a person who uses GitHub as their "_single-source-of-truth_"
I need a backup of GitHub issues 
so that I can work "offline".
(_either when I have no network or GH is "down"_)

## What?

Backup GitHub issues.

+ a script that lets you login to GitHub using OAuth
+ Use GitHub REST API to retrieve all issues 
+ Store issues as "flat files" in subdirectories corresponding to the GitHub URL 
e.g: if the issue is `dwyl/github-reference/issues/15` 
store it as `dwyl/github-reference/issues/15.json`
+ It does not need to "scale" it just needs to work. read: http://paulgraham.com/ds.html

Note: initially we do not need a Web-UI to let people backup their issues, 
but later we could build UI to make it more useable.

## How?

I have a _strong_ preference for using Elixir for this because we are transitioning _all_ our projects to Elixir, but given that this script does not require parallelism/concurrency it's "OK" to write it in which ever language you are most comfortable using.

**Comment by SimonLab** [comment]
Some questions and comments to try to get a better idea on how to implement the backup:

- Do we need to implement OAuth, maybe a first version can get directly the issues from the API without authentication. I think the only reason why we would want to use OAuth is to have a better number for the requests limit, we might need to know how many requests the script needs.

- Will this script run locally or on a server? In both case we need to save the issue json files asked locally.

- If we want to work offline we migth need to think how to synchronise the offline backup of issues with Github but this might be a feature needed for the next version not now.

Let's try with Elixir! The "Programming Elixir" book has already a nice example which explains how to display the first n most recent issues of a repo.

**Comment by nelsonic** [comment]
@SimonLab if we use the API without OAuth there will be a limit for the number of requests per minute/hour. you're _correct_ that this will _work_, it will just mean the person has to _wait_ for the script to run over a number of hours instead of working in a few minutes.

**Comment by jruts** [comment]
@nelsonic  that is just to play around, it is far from complete :D Elixir is too much fun not to play around with it. I do think it is rather easy to implement this mini project. If you need a ready to use github lib I would recommend [tentacat](https://github.com/edgurgel/tentacat).

**Comment by nelsonic** [comment]
@jruts thanks for the tip! https://github.com/edgurgel/tentacat looks _really_ good! 😍 
(_hope your day is going well..._)

**Comment by nelsonic** [comment]
@JMurphyWeb I think we just need to write a script that _uses_ Tentacat to fetch all the issues for an org's repos.

**Comment by nelsonic** [comment]
If we could solve _this_ issue: https://github.com/dear-github/dear-github/issues/129 
the _world_ (_of GitHub_) would be a _better place_!

**Comment by Cleop** [comment]
Closing as 'Done' in the Projects board.
