### ISSUE TITLE
Github has stopped showing/tracking issue title changes?

### ISSUE THREAD

**Issue by iteles** [dwyl/github-backup#115]
In issues where a title is changed, the change of title is no longer tracked in the flow of the issue!

I first noticed this in a private client repo so I can't link to this, but it is easily tested.
Having taken a look in one other place where I know a title was changed, it appears to have been removed from historical issues too! 💔 

Yet another use-case for gitbu!

**Comment by nelsonic** [comment]
@iteles I still see the Title Changes: e.g: https://github.com/dwyl/hq/issues/146
![image](https://user-images.githubusercontent.com/194400/37880717-7ecd0010-3084-11e8-83a2-545148edb6ab.png)

Maybe you're being A-B tested on ... 🙄

**Comment by iteles** [comment]
😱 That sucks so badly!! I still don't see them 😭 

Anyone else in my ⛵️ 
<img width="608" alt="screen shot 2018-03-25 at 23 33 13" src="https://user-images.githubusercontent.com/4185328/37880742-f9854ede-3084-11e8-8e58-88d0b742154d.png">

**Comment by SimonLab** [comment]
@iteles how did you test the title change feature, was it on your machine?
I sometimes forget to run ngrok or to update the url in the github app settings. Ngrok also stop the connection after a (long) period of time but it's worth checking it, especially if you change your wifi/network

**Comment by nelsonic** [comment]
@SimonLab, Inês just updated the title on GitHub (_without having the App running on `localhost`_)
and the title change _history_ was not visible in the UI ... 🙄 
(_it's not related to GitBu ... but rather to the GitHub UI A/B test ..._)

**Comment by SimonLab** [comment]
sorry get it now!
I'll check on my side too. Otherwise we haven't tracked the any title changes yet because Github is (was?) displaying the information but it can't hurt to save the history of the title changes

**Comment by nelsonic** [comment]
@iteles is this still an issue?

**Comment by iteles** [comment]
I mean, I still don't see them, but if everyone else does then... closing!

**Comment by nelsonic** [comment]
@iteles could it have been something to do with your Chrome Extension?
Did you try in Firefox or an Incognito (no Extensions) window?

**Comment by iteles** [comment]
Urgh. It was literally the _one_ Chrome extension I have: https://github.com/sindresorhus/refined-github

Disabled.

Opening an issue there. Thanks @nelsonic

**Comment by nelsonic** [comment]
@iteles I _suspect_ that hiding Title changes is a _feature_ in that Ext ... 👍 
glad you "figured it out" ... 😉
