### ISSUE TITLE
Incorrect command in readme

### ISSUE THREAD

**Issue by RobStallion** [dwyl/github-backup#116]
```
mix deps.get && cd assets npm install && cd ..
```

This command in the readme currently gives the following error in the terminal 
```
cd: too many arguments
```

Appears to be missing a set of `&&`. It should read 

```
mix deps.get && cd assets && npm install && cd ..
```

**Comment by nelsonic** [comment]
@RobStallion great spot! thanks for opening this issue. if you have time to fix, please do. 👍

**Comment by RobStallion** [comment]
@nelsonic will do 👍
