### ISSUE TITLE
Phoenix vs Plug/Cowboy

### ISSUE THREAD

**Issue by SimonLab** [dwyl/github-backup#12]
Should we use Phoenix or implement "just a simple" server with Plug and Cowboy?

Our first thought was to use only Plug and Cowboy to create server:
- Only create the files, modules and function necessary for the project, ie simple file structure
- Less cluttered files
- Easier to get an overview of  the project
- Implement only what is needed

However for a long term project Phoenix might be a better choice:
- File structure defined for you
- Provide standard and guidelines for your code
- Package features, especially Ecto and Schema for saving data

At the end I agree that on a long term project Phoenix might be a better choice.

**Comment by Cleop** [comment]
A nice comparison from this article: https://shankardevy.com/code/create-elixir-web-app-using-cowboy/
- Phoenix uses a library called Plug, that takes care of low-level plumbing with Cowboy and frees you from worrying about how to configure Cowboy.
- Your router configurations are much cleaner in Phoenix. Thanks for meta programming in Elixir, you can write routes without making any one mad.
- Plug provides several small independent functionalities that are common in web so you can pick and choose what you need with no bloat.
- Phoenix which is build on top of Plug, provides a clean and uniform way to deal with request and if you could understand how Plug works, you can understand most of Phoenix.
- With Phoenix, you can get most of your tasks done without touching a line of Erlang code and do everything with Elixir. That's a great boost to productivity.

**Comment by nelsonic** [comment]
@SimonLab here's a "_proxy-question_": 
how long did it take you to "grok" the codebase in https://github.com/dwyl/hits-elixir ?

It is my _opinion_ that a Phoenix App will be _more maintainable_ than an Elixir-Cowboy one.

**Comment by SimonLab** [comment]
Because the lib doesn't contain a lot of file:
![image](https://user-images.githubusercontent.com/6057298/36390026-58940d0e-1599-11e8-80f6-7eabf6bf0054.png)
it was quiet easy at the end to understand the flow of the application by just having a quick look at these files.
Also the main content of the files is documentation :+1:  The main file (https://github.com/dwyl/hits-elixir/blob/master/lib/hits.ex) only contains 7 functions of a few lines of code! That's why it's very easy to grasp the logic of the code.

It took me more time as I dive directly into the documentaion of Plug and Cowboy and watch a few youtube videos on this but I could have been faster to just learn by tweaking the project directly.

However ```hits-elixir``` is a relatively small app and as soon as more complex functions are needed it can become more tricky to navigate between files. Phoenix give a canvas for bigger project to follow in this case.

**Comment by Cleop** [comment]
We chose to go with Phoenix rather than Cowboy/Plug given our longer term vision for this project. Phoenix has now been set up. @SimonLab - are you happy to close this?

**Comment by mmacheerpuppy** [comment]
I'd disagree. I think you shouldn't look to phoenix to solve the problem of how to structure your application. Elixir doesn't care how you structure your application. Neither does phoenix. I'd recommend reading up on domain driven design if you are looking for a maintainable project structure to enterprise scslem
