### ISSUE TITLE
Create Github App

### ISSUE THREAD

**Issue by SimonLab** [dwyl/github-backup#19]
The steps to follow for creating a Github app are described here: https://developer.github.com/apps/building-github-apps/creating-a-github-app/

Some points to keep in mind:

- [x] Give a name to the app, for the MVP we maybe just use "GIBU" for the moment and once we have decided on the final name we can update it on the Github App settings
- [x] Webhook URL: It's the endpoint where we want Github to send notifications to. It will use the domain name that we will have choosen (ex: https://gibu.co.uk) + the endpoint defined on our Phoenix server. This endpoints needs to match a Post request routes, on dwylbot the ```/event/new``` routes is used (see https://github.com/dwyl/dwylbot/blob/91b65bc4c9e57ec935f503fd82e4c39b5cb76252/lib/dwylbot_web/router.ex#L25), should we use the same name or is there a better one? see also https://developer.github.com/webhooks/
- [x] webhook secret: This can be used to make sure that the post requests received by the server are from Github webhooks. From an MVP perspective I don't think this is necessary but we should definitely define a token later on (or should we do it now :thinking: ?) see also: https://developer.github.com/webhooks/securing/
- [x] Permissions: we should only use the ones we need! Issues

To test locally the app, each contributor will need to create their on Github App, otherwise we need to find a way to share the same webhook url with developers (not sure if this is possible). To make a localhost Phoenix server accessible by Github we use ngrok, see https://github.com/dwyl/dwylbot#run-a-dwylbot-server and https://developer.github.com/webhooks/configuring/#using-ngrok

**Comment by nelsonic** [comment]
@SimonLab looks good. thanks. 👍
