### ISSUE TITLE
initialise Phoenix server

### ISSUE THREAD

**Issue by SimonLab** [dwyl/github-backup#20]
- [x] Create new project:
 ```
  mix phx.new gibu
  cd gibu
  mix ecto.create
  mix phx.server
  ```
- [x] Define a post endpoint which will receive the Github events
- [x] As a first "dummy" step to make sure that the server is running properly and that it receive the Github post request, the controller could just log the type of event

I think these steps will provide the foundation to build the logic of the application and I found it sometimes easier to think of the next steps when we have already something running

**Comment by nelsonic** [comment]
@SimonLab agree with these steps.
Only thing I would alter is: call the App `"app"` to be _generic_.

**Comment by Cleop** [comment]
@nelsonic - not sure if you want to test this by running locally or not. If happy, please close 😄

**Comment by Cleop** [comment]
Closing as 'Done' in the Projects board.
