### ISSUE TITLE
Determine and implement designs/UI/UX

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#23]
What are our designs for the project? What will it look like? Need to think about this and then implement it.

Summary of comments on this issue: it has been decided that for the MVP the UI will be a copy of the github 'cards' for comments that users are familiar with. The page will display a list of them in order from the top of most recent to oldest. The most recent comment will have a white background on the text whereas all of the other ones will have a greyed out background to show that they are previous versions.

Create a copy of the github comment card including:
- [x] Top banner with username, timestamp/date and user type and arrow pointing to avatar
- [x] To the left of the top banner the user's avatar
- [x] Text box which is either white for the most recent comment or grey for previous comment versions
- [x] Make all of these requirements responsive and suitable for comments which are both long and short

**Comment by nelsonic** [comment]
@Cleop we need _someone_ (_any volunteers_? 🤔 ) to do an investigation into the _simplest_ UI for displaying a _history_ of records. 
For MVP we can simply list "cards" (_copy the UI directly from GitHub_)
with the revisions shown _below_ the _current_ (_most recent_) version of a comment.
We can use a `background-color` to distinguish the _previous_ versions from the _latest_.
That's pretty much it for MVP.

**Comment by Cleop** [comment]
Google docs example:
![image](https://user-images.githubusercontent.com/16775804/36746476-507e94ca-1bea-11e8-80f6-1261ca056e1a.png)

**Comment by nelsonic** [comment]
If we could _highlight_ the changes from one version to the next it would be _amaze_ 
but _for now_ we just want to _display_ the previous versions using a "visual cue". 👍

**Comment by Cleop** [comment]
One vision of the UI - the issue page displays as normal and at the bottom of each comment is a link with the number of revisions. When clicked this link takes you to our site.
Then either our site will load a page with just versions of that comment on and they're all stacked chronologically OR our site loads a page that resembles the issue page (so you can see all of the comments side by side, which I think would make understanding the flow of conversation easier). In this second example I would display the current comment and when you click the revisions link another copy of it pops up below automatically displaying the penultimate version of the comment. However using the dropdown you can switch between versions. On the card itself, changes are highlighted in colour or with underlines/strikethroughs or both according to what has been added/removed.
![image](https://user-images.githubusercontent.com/16775804/36747149-1cd5149e-1bec-11e8-9347-2db5969dd2bd.png)

Is this along the lines of what you were thinking @nelsonic?
Would underlines/strikethroughs and colour changes be relating to the previous version of each comment or in relation to the most recent version of the comment? In my mind I would have it relating to the previous version of the comment so you can track who made what changes when.

**Comment by nelsonic** [comment]
@Cleop my _preference_ would be to _replicate_ (_all_) the issue comments chronologically 
and simply display the revisions (_with `bg-light-gray`_) _below_ the "latest" version of the comment. 
I don't think GitHub will be "offended" if we "reproduce" their UI for comments. 
We can _improve_ it by making it more _mobile-friendly_.

**Comment by Cleop** [comment]
These are mock-ups of the github page and then our site. I've not edited the copy on the comment versions but in reality they would be different text.
![image](https://user-images.githubusercontent.com/16775804/36783471-fe9aedcc-1c73-11e8-95ae-5a0e9677332f.png)
![image](https://user-images.githubusercontent.com/16775804/36783491-0daf2be8-1c74-11e8-9382-b16e16cf4749.png)

**Comment by nelsonic** [comment]
@Cleop _exactly_. 🎉

**Comment by Cleop** [comment]
@nelsonic - my assumption is that for the MVP these fields aren't needed:
![image](https://user-images.githubusercontent.com/16775804/36787604-a207032a-1c82-11e8-9d3b-e0929e38af9c.png)
As we'd have to include the functionality that goes with them. That is aside from the owner/member field, should we include that field?

Also do we want to display reactions and would we therefore be showing reactions acquired over time or just the most recent of reactions?

**Comment by nelsonic** [comment]
Yeah, we won't need to _edit_, add a "reaction" or `delete` a comment in the GIBU DB/UI until we implement #4 👍

**Comment by Cleop** [comment]
I am going to paste here some color options for the gray tone for the 'old' comments:
 background-color: #dddfe1;
![image](https://user-images.githubusercontent.com/16775804/36788378-9e88c118-1c85-11e8-9523-82df741cd761.png)

**Comment by nelsonic** [comment]
@Cleop see: http://tachyons.io/docs/themes/skins search for: `bg-light-gray`
as for the "card header" it should be a _shade_ darker than the comment body so: `bg-moon-gray`
(_we can always **change** this with User Feedback_) 👍

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/36795997-5704846e-1c9c-11e8-859e-8f33c0d4d7c2.png)
Used this as the basis for creating my css arrow: http://www.cssarrowplease.com/

**Comment by Cleop** [comment]
What shall we do with the member type's display on mobile?
![image](https://user-images.githubusercontent.com/16775804/36801514-499c5c26-1caa-11e8-9010-e677e82f943b.png)
At the moment I was using float right to display it when it's on one line but when it has to go onto two lines it doesn't look good.

**Comment by nelsonic** [comment]
looks good. 🎉
