### ISSUE TITLE
Saving Comment Richtext Data to S3

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#31]
Relates to #18 

We are going to use S3 to save the text of comments.

Implementation suggestion from @nelsonic: 
> Our Phoenix App will create a {commentid}.md file in the S3 bucket using [ex-aws](https://github.com/ex-aws/ex_aws) and store a reference to it in the comment_history table.

Implementation suggestion from @SimonLab:
> Create a function to save a json into s3,  see: https://medium.com/founders-coders/image-uploads-with-aws-s3-elixir-phoenix-ex-aws-step-1-f6ed1c918f14 using a specific dependency to upload the image, we can check if this package is still up to date and create a function which uses it.

Both use ex-aws, but one is suggesting saving as .md files, the other as json files.

**Comment by Cleop** [comment]
ex-aws says:
'Elixir streams to automatically retrieve paginated resources.'

**Comment by Cleop** [comment]
This morning I worked with @SimonLab to try and debug my code from yesterday. We decided to proceed with my initial code from the ex-aws repo before we look at JC's code. Despite the repo implying that the config is done automatically: `ExAws by default does the equivalent of...`, we manually added in the config and the server now runs.

We then manually uploaded something to s3 as the command provided on s3: 
>With these deps you can use ExAws precisely as you're used to:
>`# make a request (with the default region)`
>`ExAws.S3.list_objects("my-bucket") |> ExAws.request`

 sounds as though it could be listing rather than uploading resources and so there is something in our bucket to list.

We then logged the result of this command and get this:

![image](https://user-images.githubusercontent.com/16775804/36726537-0561a1e0-1bb2-11e8-803a-83e883387360.png)

We checked that the env vars have been set and they have. So next I'm going to look into why this may be occurring.

**Comment by SimonLab** [comment]
![image](https://user-images.githubusercontent.com/6057298/36739537-15fed510-1bd8-11e8-8c88-65fc66a40583.png)
I'll need to update manually elixir to be able to use aws with Elixir

**Comment by iteles** [comment]
This is probably where learnings from this issue should go 😊 https://github.com/dwyl/learn-amazon-web-services

**Comment by Cleop** [comment]
@nelsonic @SimonLab - once we get this up and running, do we want to save our files as `.md` or `json` files?

**Comment by nelsonic** [comment]
@Cleop _good question_ I've been thinking about this ...
We can make the issue comment history "lookup" both _faster_ and _cheaper_ if we use `.json` 
_specifically_ the file should be `{issue_id}.json` and we should use the format:
```json
{
  "comment_revision_id": "escaped rich text",
  "comment_revision_id": "escaped rich text, etc ..."
}
```
This way we only need to retrieve a **_single_ file** from `S3` and display it on a page. #23

**Comment by SimonLab** [comment]
After creating new credentials for my account on aws I can access the bucket inforamtion:
![image](https://user-images.githubusercontent.com/6057298/36785036-67fa31ba-1c79-11e8-946d-360029a9fa95.png)

**Comment by nelsonic** [comment]
@SimonLab so you are getting a `404` error when attempting to _view_ the file you uploaded?

**Comment by SimonLab** [comment]
@nelsonic the 404 error is a conflict on the configuration of [ex-aws](https://github.com/ex-aws/ex_aws)
I haven't try yet to download the file (the url is not displayed when I manage to get some basic information). We need to make sure first that the configuration of the ex-aws is done properly and understand where to use the environment varialbe (in the config or directly on the ex-aws functions calls)

**Comment by nelsonic** [comment]
@SimonLab which _branch_ are you working on?
(_I only see this issue referenced in Cleo's commits..._)
I can try and take a look if you need a "_second pair of eyes_"...

**Comment by SimonLab** [comment]
I'm working on https://github.com/dwyl/github-backup/tree/save-to-s3. At the moment I'm having a better look at the ex-aws code to try to undersrtand how the requests are build.
I'm using this config: https://github.com/dwyl/github-backup/blob/5dc3126b867b88cff6c2fdbd2d5a4bdbe1ca4020/config/config.exs#L32-L39

Then on the on the ```get_files_buckets```: https://github.com/dwyl/github-backup/blob/5dc3126b867b88cff6c2fdbd2d5a4bdbe1ca4020/lib/app_web/controllers/aws/s3.ex#L17 if you pass ```nil``` has a parameter to the function you should be able to get some information logged in on the terminal (we are calling the function on the home page at the moment: https://github.com/dwyl/github-backup/blob/5dc3126b867b88cff6c2fdbd2d5a4bdbe1ca4020/lib/app_web/controllers/page_controller.ex#L7)
But the documentation ex-aws is not clear and they suggest to pass the name of the bucket to the function but this return a 404 error.

I'm wondering if ex-aws is necessary, maybe we could simplify the request to aws by just using httpoison for example

**Comment by SimonLab** [comment]
I still can't find out why ```s3.list_objects``` with the correct bucket name as a parameter return a 404 NoSuchKey. I start to think it might be an issue with the way the bucket has been created on s3? @nelsonic I'd like to create another bucket to see if I still have the same error, is it ok or do we need to pay more for this?

Otherwise listing all the items of the bucket is not really a function we will use so I might try to upload a file to the bucket first and try to get the url of this file. Then try to read the file with our current credentials

**Comment by nelsonic** [comment]
@SimonLab you can create _unlimited_ buckets without incurring any cost 
(_provided you don't store large files in them..._)

**Comment by SimonLab** [comment]
I have a similar error with a new created bucket:
![image](https://user-images.githubusercontent.com/6057298/36795176-3f2c85fa-1c9a-11e8-81b3-5f373bf1cb54.png)
Which let me think that the error is due to our code instead of aws directly

**Comment by SimonLab** [comment]
By defining the region directly into the S3 function call I manage to get the list of items and to create a new item in a bucket:
```
S3.put_object("sauvegardedata","test.json", "{\"yo\": \"yeaaa\"}") |> ExAws.request(region: "eu-west-2") |> IO.inspect
```

The configuration contain only the basic credentials:
```
config :ex_aws,
  access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
  secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY")
```

**Comment by Cleop** [comment]
Found this article with some nice documentation:
https://alexgaribay.com/2017/01/20/upload-files-to-s3-with-phoenix-and-ex_aws-2/

**Comment by Cleop** [comment]
@SimonLab - we have got this working on the save-to-s3 branch. Are we in a position to create a PR for this or is there anything blocking us from doing this?

**Comment by Cleop** [comment]
@SimonLab - would you like to close this issue as you created it and it's a technical one?

**Comment by SimonLab** [comment]
The text of the comments is now saved in S3 with the following stringify json format: {version_id: "text comment", ...}
