### ISSUE TITLE
Bug: Comment box not consistent size on Simon's laptop

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#38]
![image](https://user-images.githubusercontent.com/16775804/36842389-744db804-1d43-11e8-9bee-e661e0851278.png)
- [x] Fix inconsistent width on comment boxes on some wider screens (tested using monitor in FocusHub)

**Comment by Cleop** [comment]
The fix for this has been implemented using a precise min-width measurement. Tachyons does not currently have min-width values, see https://github.com/tachyons-css/tachyons/issues/221.

We need a min-width in this instance because using a standard width alone does not work on mobile as the width of the element goes right to the edge of the screen. The reason for this is because the size of the comment part of the element does not fit inside its container because the way it is fitting the avatar in is using margin-left as the avatar is placed using position absolute. As a result this margin is not being accounted for in the width of the item and it is over-spilling its box.

So either we can roll with the precise min-width or we could potentially try flexbox as an alternative.

**Comment by nelsonic** [comment]
@Cleop this is "_fine_" for now. 
@SimonLab please confirm it looks "OK" for you. 
thanks. 👍

**Comment by SimonLab** [comment]
@Cleop @nelsonic looks good on my x230 :+1:
