### ISSUE TITLE
Display versions of the issue description

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#47]
We are now saving versions of the first comment in an issue (the issue description) into our DB. Now we want to display these on our front end.

In order to do this we need to:
- [x] generate a new comment 'card' for each version
- [x]  make all cards that are not the latest card grey in the textarea
- [x] Order the cards with most recent top
- [x] Get distinctive date
- [x] access the copy from S3 and display it
- [x] access the meta data from the DB and display it

For the time being this will not include user data which we have not yet got in our schema, see #46.

**Comment by nelsonic** [comment]
looks good. 🎉
