### ISSUE TITLE
What information/data do we want about issues?

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#5]
From #1:
> I need a backup of GitHub issues
so that I can work "offline".

Thought it might be good to start creating a list of fields that we want about the issues. I know that some work has already been done using the github API and issues in https://github.com/dwyl/tudo so maybe thinking about the fields will help us see if what's been done there is of any use.

So far we've discussed the importance of recording:
History of:
- [x] Comment text
- [x] Comment author
- [x] Comment time/date
- [x]  Issue title
- [x] Issue description - not sure if this is a different field to comments or if they're considered the same

**Are these sufficient for now as an MVP starting point?**

Or do we need to record info like commits on an issue, labels, assignment or associated milestones? Or even more github detail?

**Comment by nelsonic** [comment]
@Cleop this is a _great_ starting point. We can always _add_ to it later. 👍

**Comment by Cleop** [comment]
@nelsonic - for the first iteration do you think we should include/exclude comments/reviews on PRs?

**Comment by nelsonic** [comment]
@Cleop yeah, for the _first_ iteration we only want to capture the changes in issues comments.
That is _more_ than enough to get started with the _rest_ of the plan. 👍

**Comment by Cleop** [comment]
| Users          |
|---------------|
| ID       |
| Github handle |

| Organisations |
|---------------|
| ID       |
| Organisation name |

| Repositories |
|--------------|
| ID      |
| Repo name    |

| Issues                     |
|----------------------------|
| ID                         |
| Github-description ID          |
| Issue number (from github) |
| Opened by author ID        |
| Updated at (time/date)     |
| Description                |
| Repository ID              |

**Comment by nelsonic** [comment]
@Cleop this looks good as a starting point. 👍

**Comment by SimonLab** [comment]
I think we need to save the s3 url of the file in the database for each edit of the issues and comments.
I was thinking a structure like the following:
![image](https://user-images.githubusercontent.com/6057298/36532423-9a6243f6-17b8-11e8-9288-a7426046342f.png)

**Comment by nelsonic** [comment]
@SimonLab agree that we need to have a "history" table.
But it's _unclear_ (_to me_) what the distinction between `issue_history` and `comment_history` is. 
Also, I think _all_ `comments` should be in the `comment_history` table even if there are no _edits_ to it.

**Comment by SimonLab** [comment]
agree we can create only one "history" table where an entry of this table can refer either to the issue or to the comment table. As soon as a new issue or a new comment is created the history table will have a new entry wich will also contain the url of the s3 file.

**Comment by Cleop** [comment]
Closing this as we're now recording all of the data in the description of this issue.
