### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by nelsonic** [dwyl/github-backup#54]
As a `product owner` (_or `developer`_) 
I `want` to know the _stats_ on how people are finding & navigating/using App/Project
`so that` I know if people are discovering and _using_ the App.

+ [x] Enable Google Analytics on the App/Site using @dwyl account (_ask @iteles_) 

See: https://github.com/dwyl/learn-google-analytics

**Comment by iteles** [comment]
Linked to #13

**Comment by Cleop** [comment]
Shall I set this up pointing to the heroku account for now? Or is #13 now sorted and we've bought a domain?

**Comment by Cleop** [comment]
Closing as this is merged and a 'technical' issue. I've tested again on GA:
![image](https://user-images.githubusercontent.com/16775804/37399458-a5d33b98-2779-11e8-920a-085888bd8692.png)

**Comment by nelsonic** [comment]
@Cleop thanks for setting this up and confirming it's working with a _screenshot_! 🥇
