### ISSUE TITLE
Amend UI for issue title at the top of comment page 

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#59]
As a user
I want to be able to recognise the title of the issue as being the title of the issue
So that I can understand the context of the comment versions that I am looking at.

This is currently how the top of the page looks:
![image](https://user-images.githubusercontent.com/16775804/37098526-f72b16b4-2215-11e8-9eb9-ca2ca649ace0.png)
It's not very obvious that the second heading is the title of the issue. Perhaps we could help distinguish it more by making it resemble the UI from github more closely? This is the UI from github:

![image](https://user-images.githubusercontent.com/16775804/37098350-997a90b2-2215-11e8-92fb-05fedc23877a.png)

As a starting point I would suggest:

- [x] Left align the text
- [x] Have a fine rule drawn underneath it

**Comment by Cleop** [comment]
I've made the changes, however the sections are not quite in line because one of them has expanded outside of its dimensions:
![image](https://user-images.githubusercontent.com/16775804/37341979-318dbf6a-26bb-11e8-969a-0bb72bbb6047.png)
I will now look into this to fix it.

**Comment by nelsonic** [comment]
@Cleop thanks for fixing. 👍
