### ISSUE TITLE
What can we "recycle" from Tudo?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/github-backup#6]
The `tudo` application already has _some_ of the functionality for this project ...
see: https://github.com/dwyl/tudo

@Cleop do you have time to _run_ the `tudo` app locally and go through the code to see what can be re-used...? (_thanks!_)

**Comment by Cleop** [comment]
I took a little look into `tudo` but sadly came across more hurdles than help! I was experiencing a number of errors on localhost which I've recorded in issues: https://github.com/dwyl/tudo/issues/264 and https://github.com/dwyl/tudo/issues/263. 

That's not to say that `tudo` won't be of use to us at all but rather it's worth noting that there are some bugs present.

**Comment by nelsonic** [comment]
@Cleop thanks for taking a look and opening those issues. 👍 
Agree that it would be useful to speak to Simon.
Would you mind doing it as a "Meet" call?

**Comment by SimonLab** [comment]
I think we can adapt and get inspiration from [dwylbot](https://github.com/dwyl/dwylbot):
- use Github App
- use Github API
- run with Elixir (and Phoenix)

**Comment by nelsonic** [comment]
@SimonLab Agreed. (_sadly, not much is "re-useable" from "Tudo" ..._) 
The absence of Docs _super_ disappointing. 😞 
Closing.
