### ISSUE TITLE
How do we want our backup site to link back to github?

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#60]
We know how users will get to our backup site from github (see #14) but I was wondering:

**Do we want/ how do we want our content to link back to the github main site?**

Thoughts:
- We may not want people to return to github at all because we want them to navigate around our site
- We may want to offer them links back to github whilst we're at MVP stage and can't allow them to navigate their issues/comments using our platform alone (but we could remove these links later)
- Once we implement #14 we may choose to open our site in a new tab so that people can easily cross reference the issue and flow of conversation on it with our backup history (although new tabs are not good practice for accessibility).

What do others think? @SimonLab @nelsonic

**Comment by nelsonic** [comment]
@Cleop _thanks_ for opening this question! (_it's a good one to discuss_)
For MVP we _probably_ don't need to worry about helping people to _navigate_ back to GitHub as they will likely just use their browser "back button".
However as a future _enhancement_ we could get user _feedback_ 
on what the most intuitive way to navigate is.

**Comment by Cleop** [comment]
Closing as this requires no immediate action and any further development on this will be prompted by user feedback.
