### ISSUE TITLE
Create a dwyl navbar/banner

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#61]
As a user
I want to be able to recognise the brand of the app I'm using
So that I can learn more about or contact them if I'm curious

On the dwyl feedback app we use the following banner:
![image](https://user-images.githubusercontent.com/16775804/37103022-2d4e4b5c-2221-11e8-906c-82bfe31b4a38.png)
https://dwyl-feedback.herokuapp.com/feedback/new

@iteles suggested we implement the same banner for this project (without the forum link). 

- [x] Create the banner in the layout file
- [x] Make the dwyl logo link to the homepage

**Comment by iteles** [comment]
Code here: https://github.com/dwyl/feedback

**Comment by nelsonic** [comment]
Banner looks good for MVP. 😍 
We will need a distinct GitBu _logo_ when we "officially launch" this,
feel free to open a _separate_ logo-specific issue. relates to https://github.com/dwyl/hq/issues/435 😉
