### ISSUE TITLE
Change the comment time/date format to match Github's

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#62]
Currently we display times/dates like this:
![image](https://user-images.githubusercontent.com/16775804/37103607-86621f9c-2222-11e8-8809-3c00402c6ebf.png)
![image](https://user-images.githubusercontent.com/16775804/37103696-b973d376-2222-11e8-8994-919917286354.png)

Whereas we display them like this with dates as numbers and never as a reference to how long ago (for more recent posts):
![image](https://user-images.githubusercontent.com/16775804/37103655-a1d96988-2222-11e8-9b1c-ca52fa6138a7.png)

If we are trying to stick as closely as possible to github's UI then we could update this. One option to achieve this would be to use the Timex library: https://hexdocs.pm/timex/Timex.html

```
Timex.from_now(Timex.shift(DateTime.utc_now(), days: -2))
"2 days ago"
```

Or if we think the library is too bulky for this use case then we could write our own custom version.

**Comment by nelsonic** [comment]
@Cleop I actually _prefer_ the precise date-time.
could we not have _both_ displayed? e.g:
```
2 days ago (2018-03-06 17:35:38)
```
So it shows the _exact_ time that the edit/update was made.

**Comment by Cleop** [comment]
@nelsonic, as you wish. So far I've just been following the 'replicate github' notion but I'm happy to have just precise date-time or both if it's not too cluttered/ users want it.

**Comment by nelsonic** [comment]
@Cleop yeah, stick with "replicate GitHub UI".
We can _always_ add the precise date as a "tool tip" so the UI (_on Mobile_) is not cluttered.
