### ISSUE TITLE
Display checkboxes correctly as checkboxes

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#69]
Currently checkboxes display like this:
![image](https://user-images.githubusercontent.com/16775804/37157444-cc584472-22e0-11e8-802e-fab81c657cf6.png)
when they should display like this:

- [ ] checkbox

Relates #53 

As a user
I want to be able to see the UI I am accustomed to on github
So that I can easily understand the comments I am reading.

This has been created as a separate issue so that it can be prioritised separately.

**Comment by SimonLab** [comment]
This is linked to Github Flavored Markdown: https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by Cleop** [comment]
Earmark only currently partially supports GFM and this does not include checkboxes/task lists:
https://github.com/pragdave/earmark/issues/126

I have however found in the options how to support line breaking.

**Comment by nelsonic** [comment]
@Cleop great work! 🎉
