### ISSUE TITLE
Set up Issue endpoint and page

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#75]
Relates: #14 

As a user who has clicked on the meta table on github
I want to be able to see an overview of the history of my issue on the backup site
So that I can dig deeper into the comments/histories of interest to me

- [x] Create issues endpoint/page
- [x] Get the comments text from s3
- [x] Get the comment details from the DB
- [x] Display all of the comments of a given issue id on that page

@nelsonic - should we show every version of every comment or just the latest version of each comment?

**Comment by nelsonic** [comment]
@Cleop _most_ comments will not be edited and the ones that _are_ will only have a _few_ edits.
For now let's just display _everything_ on a single page to _reduce_ the amount of "functionality" we need to have i.e. a _single_ page for everything for that issue.

**Comment by Cleop** [comment]
This is now working however, credo is complaining about the duplicate functions that exist in the issue and comment views. So now I'm going to read up on how to get rid of this error by sharing the functions.

**Comment by Cleop** [comment]
I tried to implement the stackoverflow global view concept but am getting this error, the same error that the elixir forum question was talking about:

![image](https://user-images.githubusercontent.com/16775804/37300224-559d7b50-261d-11e8-8c2a-32216deb8b9a.png)

This was the given reason for this error on the elixir forum question:
> Since your SharedView module also has this quote block injected, **it’s trying to import itself,** which is causing the error. The easiest option is to my those function, i.e. my_func/1 to another module that you import in the view block instead of defining it on SharedView

However, I don't fully understand the solution.

Also, I don't think I've done what was at the bottom of the stackoverflow implementation here as I didn't really understand what they were saying:
![image](https://user-images.githubusercontent.com/16775804/37300332-9a286af0-261d-11e8-8aae-3112105738c5.png)

**Comment by Cleop** [comment]
Managed to fix this one with @RobStallion.

We've created a helpers folder in `app_web` which contains the functions:
![image](https://user-images.githubusercontent.com/16775804/37340141-0579f02a-26b5-11e8-98ad-3bdb532bb0bb.png)

Then each view is requiring this file in:
![image](https://user-images.githubusercontent.com/16775804/37340161-1b2b77c2-26b5-11e8-9834-bb1df9fd8869.png)

We also tested this by putting it in web.ex which worked, so if we want them globally we can do this in the future.

**Comment by RobStallion** [comment]
@Cleop Sorry for the delay getting back to you.

**Comment by nelsonic** [comment]
@RobStallion thanks for helping! 🎉 
@Cleop looks good! 😎
