### ISSUE TITLE
Add 'bin' icon to when a comment is deleted event

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#78]
Relates: #58 

- [x] Add fontawesome to the project
- [x] Add this https://fontawesome.com/icons/trash?style=solid 'trash'/'bin' icon inside of a circle to the comment deleted message in place of the github UI 'X' for this kind of event:

![image](https://user-images.githubusercontent.com/16775804/37088515-8aa0405c-21f5-11e8-9762-939cac1c0475.png)

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/37300917-1a4e829a-261f-11e8-8dc5-77c69d178850.png)

**Comment by nelsonic** [comment]
@Cleop stoked with this. looks good. thanks!
