### ISSUE TITLE
Test Existing Tools/Services?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/github-backup#8]
https://backhub.co

**Comment by Cleop** [comment]
### Backhub
- Plans start at $9 USD for up to 10 repository backups
- Github app
- Same flow as we have outlined here: #7 - install the github app, followed by authorise the application to have access to your repos.

**Comment by nelsonic** [comment]
@iteles can we do the 14 day trial to review the UI/UX?

**Comment by nelsonic** [comment]
@Cleop in the course of your research did you find any _other_ tools that might be _similar_...?

**Comment by Cleop** [comment]
[github-backup](http://github-backup.branchable.com/) which backs up any public repository, or all repositories owned by a particular user.
[GitHub Records Archiver](https://github.com/benbalter/github-records-archiver), which backs up all of an organization's public repositories.

And of course -
BackHub, which creates daily recurring backups of your repositories with snapshots up to 30 days back in time. BackHub is available in GitHub Marketplace.

**Comment by nelsonic** [comment]
@Cleop _thanks_ for adding these links. 
`github-backup` was the first one we investigated, it's written in Haskel and _not_ "beginner friendly".
![image](https://user-images.githubusercontent.com/194400/36421313-ea9ae6b4-162f-11e8-8548-f528914822a1.png)

https://github.com/benbalter/github-records-archiver is "General Purpose" for downloading a _snapshot_ of all GitHub data:
![image](https://user-images.githubusercontent.com/194400/36421380-180e1b66-1630-11e8-86c7-555c658e1c3a.png)
The use-case is different from what _we_ are proposing, namely "_issue comment edit history_".

https://github.com/github/backup-utils made by GitHub themselves is intended for "Enterprise" clients:
![image](https://user-images.githubusercontent.com/194400/36421524-a65fc1a8-1630-11e8-81d1-68464b3f6f51.png)
![image](https://user-images.githubusercontent.com/194400/36421532-ab821636-1630-11e8-94d9-83d4fc677435.png)
(_which may **someday** be our "target" but not for the foreseeable future..._) 

> I think we have a _distinct_ use-case from existing _partial_ "solutions".

**Comment by Cleop** [comment]
@nelsonic - are you happy with this research meaning that this issue can be closed or is there more that you would like to be done?

**Comment by nelsonic** [comment]
@Cleop yes. 👍
