### ISSUE TITLE
Backup everything since a repo has been created?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/github-backup#9]
Should the Github App back up all the issues and comments since the creation of a repo. For example when the Github App is installed we could retreive all the existing data and save them in our database, however we won't have the history of the edit of comments.

From an mvp perspective I would only start saving new issues, new comments and new edited comments since the Github app is installed. Thoughts?

**Comment by Cleop** [comment]
Good question @SimonLab 

I would probably take a copy of all the existing open issues, that way you can capture on going conversations in comments that otherwise wouldn't be picked up. But I agree that copying closed issues could be unnecessary.

I'm open to others thoughts though

**Comment by nelsonic** [comment]
@SimonLab we won't be able to get _past_ edits (_from `before` the app was enabled_)
_however_ I do _agree_ that it makes sense to retrieve the _closed_ issues for the simple reason
that we occasionally refer to issues that are complete.

**Comment by SimonLab** [comment]
Thanks for the replies 👍 
So to recap, when the "github backup" Github app is installed on a repository, our server will receive a new "installationEvent" notification (https://developer.github.com/v3/activity/events/types/#installationevent). At this point we can then ask Github for all the issue's descriptions (open and closed) and the comments linked to these issues and save this information (in DB or files). Does this steps make sense?

**Comment by nelsonic** [comment]
@SimonLab these steps make perfect sense. thanks! 👍

**Comment by nelsonic** [comment]
@SimonLab these steps make perfect sense. 
_Perhaps_ we should open an `new` issue called "Installation" 
with a _detailed **checklist**_ of what needs to be done? 😉

**Comment by Cleop** [comment]
Articles on how to get **closed** issues from a repo:

- Uses R but says: 'In this case, I am setting “all” to ‘state’ parameter to include both ‘open’ and ‘closed’ issues.' So I think this is what we need to specify in our params to make sure closed issues are included.
https://blog.exploratory.io/analyzing-issue-data-with-github-rest-api-63945017dedc

**Comment by Cleop** [comment]
To conclude this issue, we agreed that yes, all issues (open or closed) should be backed up. This has now been put into action in #29. 

For that reason @SimonLab - please can you close this issue?
