### ISSUE TITLE
Change Google Analytics Property from 'Gitbu' account to 'dwyl' account

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#92]
When I set up Google Analytics I wasn't sure whether to create the account under dwyl or Gitbu:
https://github.com/dwyl/github-backup/issues/54#issuecomment-372629395

Having spoken to @iteles and confirmed with online research, we would prefer to have Gitbu under the same account as dwyl. Technically we could keep it as it is a separate account but @iteles and I agreed keeping it under dwyl might be tidier.

This diagram shows nicely how accounts vs. properties might be considered separate:

![image](https://user-images.githubusercontent.com/16775804/37400684-92b1add4-277d-11e8-8072-1dbf9b8157df.png)

**Key terms:**
- **An account is** your access point for Analytics, and the top-most level of organization. One or more Analytics accounts can belong to an organization.
- **A property is** a website, mobile application, or blog, etc., that is associated with a unique tracking ID. A Google Analytics account can contain one or more properties.
- **A view is** a set of specifications for tracking traffic on a single domain.

**Comment by Cleop** [comment]
I moved the property using the instructions here:
https://support.google.com/analytics/answer/6370521?hl=en
 🎉 
![image](https://user-images.githubusercontent.com/16775804/37401007-9ea450b4-277e-11e8-976a-c37842dc289a.png)

**Comment by Cleop** [comment]
Closing as complete and indicated tests in the comments above.

**Comment by nelsonic** [comment]
@Cleop got:
![image](https://user-images.githubusercontent.com/194400/37401755-08553b84-2781-11e8-8c97-3cfec3953229.png)

Will we need a new GA ID in the App?

**Comment by Cleop** [comment]
I don't believe so as I 'moved' the property rather than deleting it and creating a new one. The guide didn't specify the need to change the code and I also checked it was working after I'd completed everything.

I also believe that the UA codes are property specific because when I originally created 2 properties by mistake they had unique codes and as such, I wouldn't expect this to be dependent on the account.
