### ISSUE TITLE
Stop script injections from rendering in comments

### ISSUE THREAD

**Issue by Cleop** [dwyl/github-backup#95]
At the moment I can add a script to a comment on github and whilst it won't render on github, it will on our site.
<img src="https://user-images.githubusercontent.com/16775804/37403295-3ed50cac-2786-11e8-9058-3d95ef36f786.png" width=300px />
<img src="https://user-images.githubusercontent.com/16775804/37403308-47307cba-2786-11e8-878a-b045aa34fb14.png" width=400px/>

- [x] Prevent scripts from running

**Comment by Cleop** [comment]
https://hex.pm/packages/html_sanitize_ex will apparently help to solve this!

**Comment by nelsonic** [comment]
@Cleop looks good. thanks for resolving. 👍
